apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apple-bg-blue
  namespace: kube
  labels:
    app: kube-bg
    version: blue
    enabled: "true"
spec:
  serviceName: kube-bg-svc
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kube-bg
      version: blue
  template:
    metadata:
      labels:
        app: kube-bg
        version: blue
        enabled: "true"
    spec:
      serviceAccountName: kube-stag-pvt-cluster-wl-id
      containers:
      - name: kubebgcontainer
        image: us-central1-docker.pkg.dev/stm-01/my-app-repo/my-app:latest
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        imagePullPolicy: Always
