apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cphd-events-properties
  namespace: kube
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/70082307151/secrets/cphd-events-properties/versions/1"
        path: "apptivo.properties"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: stag-uat-app-log4j-properties
  namespace: kube
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/70082307151/secrets/stag-uat-app-log4j-properties/versions/1"
        path: "log4j.properties"

