apiVersion: v1
kind: ConfigMap
metadata:
  name: ersn-bg-config
  namespace: kube
data:
  APP_ENC_IV_V1_NEW: aunbxjmanlwvjjej
  APP_ENC_KEY_V1_NEW: 7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp3s6v9y$B&E)H@McQfTjWnZ
  APP_ENC_SALT_V1_NEW: 2s5v8y/B?E(G+KbP
  APP_REDIRECTION_URL: pc-app.profitokr.net
  BASE_URL: pc-app.profitokr.net
  BG_URL: pc-api.profitokr.net
  CERT_NAME: certificate-g1gc.p12
  CLUSTER_1: apple-new-cluster
  CLUSTER_2: apple-new-cluster
  CLUSTER_3: apple-new-cluster
  DOMAIN_NAME: profitokrs.com
  EMAIL_FROM: admin@berijam.com
  ES_AUTH_HTTP_TYPE: native
  ES_AUTH_TYPE: nativeWithSSL
  ES_CF_ID1: "10011"
  ES_CF_ID2: "10012"
  ES_CF_ID3: "10013"
  ES_CF_IP1: 10.241.0.4
  ES_CF_IP2: 10.241.0.4
  ES_CF_IP3: 10.241.0.4
  ES_CF_PORT1: "9307"
  ES_CF_PORT2: "9307"
  ES_CF_PORT3: "9307"
  FIRM_ID: "244209"
  KAFKA_URL: 10.80.0.125:9092,10.80.0.117:9092,10.80.0.229:9092
  LDAP_APPEND_DOMAIN: "N"
  LDAP_CONFIG_DN: dc=profitokrs,dc=com
  LDAP_CONFIG_DN_GROUPS: dc=profitokrs,dc=com
  LDAP_CONFIG_DN_USERS: ou=People,dc=profitokrs,dc=com
  LDAP_ENABLED: "Y"
  LDAP_FILTER_TEAMS: (\&(cn=SEARCHTEXT*)(memberUid=MEMBERUID))
  LDAP_FILTER_USERID: uid=FILTER_USER_ID
  LDAP_FILTER_USERS: cn=SEARCHTEXT
  LDAP_GROUP_NAME: cn
  LDAP_GROUP_NUMBER: gidNumber
  LDAP_LOGIN_PASSWORD: Apptivo@123
  LDAP_LOGIN_USERNAME: cn=Manager,dc=profitokrs,dc=com
  LDAP_PRINCIPAL: cn=LDAP_EMAIL_ID,ou=People,dc=profitokrs,dc=com
  LDAP_SYNC_FREQUENCY_MINUTES: "30"
  LDAP_URL: ldap://ldap-test-01.stag.internal.profit
  LDAP_USER_DEPARTMENT_NAME: departmentNumber
  LDAP_USER_EMAIL_ID: mail
  LDAP_USER_FIRST_NAME: givenName
  LDAP_USER_FULL_NAME: cn
  LDAP_USER_JOB_TITLE: title
  LDAP_USER_LAST_NAME: sn
  LDAP_USER_MANAGER_NAME: manager
  LDAP_USER_MEMBER_UID: memberUid
  LOGIN_LOGO_URL: /ng/src/assets/images/apple_maps.png
  NODE_NAME: KUBE-API
  NODE_NAME1: node1
  NODE_NAME2: node1
  NODE_NAME3: node1
  NODE_RAM: 4G
  SMTP_IP: 10.80.0.1
  TIMEZONE: America/Los_Angeles
  TOPIC_NAMES: profit-apptivodb1-email-messages,profit-apptivodb1-newsfeed-messages-4,profit-apptivodb1-newsfeed-messages-0,profit-apptivodb1-newsfeed-messages-1,profit-apptivodb1-newsfeed-messages-2,profit-apptivodb1-newsfeed-messages-3,profit-bg-process-service,profit-general-messages,PROFIT_REVIEW_EVENT
  USER_DOMAIN: profitokrs.com

