apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-deq-config
  namespace: kube
data:
  BASE_URL: pc-app.profitokr.net
  BG_URL: pc-api.profitokr.net
  CLUSTER_1: apple-new-cluster
  CLUSTER_2: apple-new-cluster
  CLUSTER_3: apple-new-cluster
  EMAIL_FROM: admin@berijam.com
  ES_AUTH_TYPE: nativeWithSSL
  ES_CF_ID1: "10011"
  ES_CF_ID2: "10012"
  ES_CF_ID3: "10013"
  ES_CF_IP1: pc-es.profitokr.net
  ES_CF_IP2: pc-es.profitokr.net
  ES_CF_IP3: pc-es.profitokr.net
  ES_CF_PORT1: "443"
  ES_CF_PORT2: "443"
  ES_CF_PORT3: "443"
  FIRM_ID: "244209"
  KAFKA_URL: 10.80.0.125:9092,10.80.0.117:9092,10.80.0.229:9092
  LOGIN_LOGO_URL: /ng/src/assets/images/apple_maps.png
  NODE_NAME: APPLE-DEQ
  NODE_NAME1: node1
  NODE_NAME2: node1
  NODE_NAME3: node1
  NODE_RAM: 2G
  QUEUE_NAME: EMAIL,ATRW,ATGP,ATGH,ATGC,ATAW,APP_SLA_QUEUE,ATAR,AEGH,AEGC,AEAW,AEAR,AEGP,AERW,ACGH,ACGC,ACAW,ACAR,ACGP,ACRW,RECURRINGJOURNALQUEUE,EmailOpenedQueue,EmailLinkClickedQueue,UnsubscribedQueue,EmailDeliveryStatusQueue,SendEmailQueue,QRWQ,QEWQ,QIPQ,QBOEXPENSESQUEUE,launch_queue,targets_queue,QBOINVOICEQUEUE,pdf_download_queue,sentFolderSyncQueue,import_ib_shipment_queue,email_event_callback_queue,INVENTORY_IMPORT_QUEUE,CampaignLauncherQueue,CampaignBlasterQueue,QBOSUPPLIERINVOICESQUEUE,GENERATE_RECURRING_INVOICE,TRIGGER_CHILD_INVOICE,ActivitiesAutoSchedulerQueue,OCSQ,OCCQ,OCWQ,AEPQ,XIEWQ,XIRW,XIPQ,XSEWQ,XSRW,XSPQ,XPEWQ,XPRW,XPPQ,CampaignSchedulerQueue,HIGHLIGHTQUEUE,RECURRING_ACTIVITY_QUEUE,RCSQ,APPROVAL_REMINDER_QUEUE,RecurringEventSyncQueue,O365RecurringEventSyncQueue,OPPORTUNITYSNAPSHOTQUEUE,JMS_EVENTS_QUEUE,emailSyncServiceQueue,JMS_EMAIL_EVENTS_QUEUE,JMS_SERVICE_EMAIL_QUEUE,TRIGGER_WEBHOOK_QUEUE,ApptivoCustomerEventWriterQueue,ApptivoCustomerRunnerWriterQueue,ApptivoGoogleCustomerPropogateQueue,GoogleCustomerHarvestQueue,GoogleCustomerRunnersQueue,GoogleApptivoWriteQueue,IMPORT_SERIAL_ITEMS,EmailImportQueue,ITEM_RESERVATION_EXPIRATION_QUEUE,emailImportProcessQueue,gsuiteEmailWatchRenewalQueue,pricingDateRangeQueue,NEXMO_EMAIL_NOTIFICATION_QUEUE,O365_sr,O365_runners_process,O365_wh_events_process,xls_download_queue,EMAIL_SEQUENCE_QUEUE,OKR_SCORE_CALCULATION_QUEUE,OKR_UPDATE_REMINDER_QUEUE,GOOGLE_SUB_RENEWAL,GOOGLE_WH_EVENTS_PROCESS,EMAIL_SEQUENCE_ACTION_QUEUE,ASSIGNMENT_ALERTS,REMAINDER_ALERTS,GENERATE_RECURRING_SUPPLIER_INVOICE,TRIGGER_CHILD_SUPPLIER_INVOICE,O365_EMAIL_SUB_RENEWAL,O365_EMAIL_WH_EVENTS_PROCESS,REVIEW_STATUS_QUEUE,OKR_EMPLOYEE_POINTS_QUEUE,BECKMAN_BACKGROUND_QUEUE_NAME,UPDATE_RECURRING_INVOICE,FALKEN_PRODUCTION_CUSTOMERS,FALKEN_PRODUCTION_INVOICE,FALKEN_PRODUCTION_ORDERS,FALKEN_PRODUCTION_ITEMS,FALKEN_PRODUCTION_PRICING,FALKEN_PRODUCTION_SHIPPING,FALKEN_PRODUCTION_INVENTORY,LDAP_BACKGROUND_QUEUE_NAME,ACCOUNT_RENEWAL_QUEUE,PROFIT_PHMUG_QUEUE,EXT_CONNECTOR_QUEUE,PLAN_UPGRADE_RENEWAL_QUEUE,PHRMS_ISQ,SLQ,GENERATE_RECURRING_WORK_ORDER,TRIGGER_CHILD_WORK_ORDER,UPDATE_RECURRING_WORK_ORDER,activemq/queue/v2/tasks/runner/writerQueue,PROFIT_MSPQ,PROFIT_FIRM_LEVEL_EMPLOYEE_POINTS_QUEUE,PROFIT_CFR_ERU,EMAIL_TO_TASK,PROFIT_PPG_QUEUE,PROFIT_PMS_RR,PROFIT_KR_DELETE_EVENT,PROFIT_PMS_RS,PROFIT_SECURITY_SYNC_UPDATE,PROFIT_CFR_AUTO_POST,PHRMS_SVQ,EXT_JIRA_MONITOR_QUEUE,PROFIT_SETTINGS_UPDATE_EVENT,PROFIT_REWARDS_POINTS_EXPIRATION_QUEUE,PROJECT_EVM_PLANNED_PROGRESS_GENERATION,AUTO_POST_REJECT_QUEUE,PROFIT_PLANNED_HISTORY_CHECKIN_TABLE_UPDATE,AWARD_APPROVAL_QUEUE,MONTHLY_AWARD_AUTO_REJECT  
  SMTP_IP: 10.80.0.1
  TIMEZONE: America/Los_Angeles
  QUEUE_STATUS: "true"
